services:
  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole
    volumes:
      - ${APPDATA}/guacamole:/config
    ports:
      - ${PORT}:8080
    network_mode: bridge
    restart: unless-stopped