services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${DATA}/nginx-proxy-manager/data:/data
      - ${DATA}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    network_mode: bridge
    restart: unless-stopped